# 应用名称
spring:
  application:
   name: xxljob.bridge

# 应用服务 WEB 访问端口
server:
  port=8080

fun:
  utils:
    xxljob:
      bridge:
        serverPath: http://xxljob.tk8s.ldx11.com/xxl-job-admin/api/
        bridgePath: http://duckdo.vaiwan.com/

xxl:
  job:
   admin:
    addresses: http://duckdo.vaiwan.com/xxl-job-admin
     #addresses: http://localhost:8080/test
    accessToken:
   executor:
    appname: xxl-job-executor-sample
    address:
    ip:
    port: 7001