# 应用名称
spring:
  application:
    name: xxljob.bridge.server

# 应用服务 WEB 访问端口
server:
  port: 8080

fun:
  utils:
    xxljob:
      bridge:
        #xxl-job-admin 的部署地址 （要求可以和 bridge server 连通）
        adminApi: http://{xxl-job-admin部署地址}/xxl-job-admin/api/
        #bridge server的部署地址 （通常主网地址,要求可以和 xxl-job-admin 连通）
        bridgePath: http://{bridge地址}/