# 应用名称
spring:
  application:
   name: xxljob.bridge.server

# 应用服务 WEB 访问端口
server:
  port: 8080

fun:
  utils:
    xxljob:
      bridge:
        adminApi: http://xxljob.tk8s.ldx11.com/xxl-job-admin/api/
        bridgePath: http://duckdo.vaiwan.com/
